### ISSUE TITLE
Release swallows test errors

### ISSUE THREAD

**Issue by tjbo** [helpscout/zero#20]
Current behaviour:
- `npm release` will hang if there are failing tests, it seems to swallow the errors

Expected behaviour:
- if there are some failing tests `npm release` should throw.

This a usability issue, because a developer might not know that they have a problem in their tests when they go to run `npm release`.

**Comment by ItsJonQ** [comment]
Under the hood, Zero runs https://github.com/sindresorhus/np

Unsure if the hanging is due to `np` or Zero's instantiation of `np`.
If it's from `np`, then there isn't much we can do about it :(

**Comment by tjbo** [comment]
I'm unsure if it was the test that was causing this, as the test wasn't failing locally. After an npm install it seemed to resolve.

Maybe next time, we can jump on a call and try to trouble shoot the issue more.
